apiVersion: v1
kind: Service
metadata:
  name: ms1-service
  namespace: ${NAMESPACE}
  labels:
    app: ms1-deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: ms1-deployment
