apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3-deployment
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ms3-deployment
  template:
    metadata:
      labels:
        app: ms3-deployment
    spec:
      containers:
      - name: ms3-deployment
        image: eu.gcr.io/fourth-memento-307608/ms3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: "gcr-creds"
