apiVersion: v1
kind: Service
metadata:
  name: ms3-service
  namespace: ${NAMESPACE}
  labels:
    app: ms3-deployment
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: ms3-deployment
