apiVersion: v1
kind: Service
metadata:
  name: ms2-service
  namespace: ${NAMESPACE}
  labels:
    app: ms2-deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: ms2-deployment
